[package]
name = "chainlink_twap_validator"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"
hdp_cairo = { git = "https://github.com/HerodotusDev/hdp-cairo.git" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs = false

[dev-dependencies]
cairo_test = "2.4.0"